### ISSUE TITLE
expires on session put

### ISSUE THREAD

**Issue by pixelpaulaus** [adonisjs/adonis-session#54]
it would be a great feature to have an expires value that can be used with the put function. As maybe you want to store something on the session but it isn't required for a long period of time, and thus it will help prevent the session data building up.

Yes you could use redis directly, but this would be easier when wanting to store something on a specific session.

**Comment by thetutlage** [comment]
Getting back a bit late, but it's not possible to have expiry for individual values with any sort of session storage and neither I am in interested in adding that level of complexity to the code base. 

Sorry :)
