### ISSUE TITLE
Missing bson dependancy

### ISSUE THREAD

**Issue by TomoGlavas** [adonisjs/adonis-session#6]
When installing fullstack-app I just got an error from adonis-session requiring missing `bson` dependency.
Adding it to main package.json fixed the issue.

Great work on the framework. <3

**Comment by RomainLanz** [comment]
Hey,

It's listed in the deps of the package.

https://github.com/adonisjs/adonis-session/blob/3d038999fc115d56e9ffd34132ed00a3b618785a/package.json#L50

**Comment by TomoGlavas** [comment]
I guess a package installer bug then. Closing. Tx.
